/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        fontFamily: {
            sans: ["Inter", "sans-serif"],
        },
        fontWeight: {
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: 700,
        },
        extend: {
            colors: {
                primary: {
                    50: "rgb(var(--primary-50))",
                    100: "rgb(var(--primary-100))",
                    200: "rgb(var(--primary-200))",
                    300: "rgb(var(--primary-300))",
                    400: "rgb(var(--primary-400))",
                    500: "rgb(var(--primary-500))",
                    600: "rgb(var(--primary-600))",
                    700: "rgb(var(--primary-700))",
                    800: "rgb(var(--primary-800))",
                    900: "rgb(var(--primary-900))",
                    950: "rgb(var(--primary-950))",
                },
                danger: {
                    50: "rgb(var(--red-50))",
                    100: "rgb(var(--red-100))",
                    200: "rgb(var(--red-200))",
                    300: "rgb(var(--red-300))",
                    400: "rgb(var(--red-400))",
                    500: "rgb(var(--red-500))",
                    600: "rgb(var(--red-600))",
                    700: "rgb(var(--red-700))",
                    800: "rgb(var(--red-800))",
                    900: "rgb(var(--red-900))",
                    950: "rgb(var(--red-950))",
                },
                "surface-0": "rgb(var(--surface-0))",
                "surface-50": "rgb(var(--surface-50))",
                "surface-100": "rgb(var(--surface-100))",
                "surface-200": "rgb(var(--surface-200))",
                "surface-300": "rgb(var(--surface-300))",
                "surface-400": "rgb(var(--surface-400))",
                "surface-500": "rgb(var(--surface-500))",
                "surface-600": "rgb(var(--surface-600))",
                "surface-700": "rgb(var(--surface-700))",
                "surface-800": "rgb(var(--surface-800))",
                "surface-900": "rgb(var(--surface-900))",
                "surface-950": "rgb(var(--surface-950))",
            },
        },
    },
    plugins: [],
};
